### ISSUE TITLE
not working on typescript files with export default from syntax

### ISSUE THREAD

**Issue by muz3** [vscodeshift/material-ui-codemorphs#3]
Hi I really like your plugin, but when I put my cursor inside my function, and I was getting the following error. I am using typescript. any suggestion what i did wrong?

Error: 
Support for the experimental syntax 'exportDefaultFrom' isn't currently enabled (3:8): 1 | import React from 'react'; 2 | > 3 | export interface ChangeCardProps {} | ^ 4 | 5 | export default function ChangeCard(props: ChangeCardProps) { 6 | Add @babel/plugin-proposal-export-default-from (https://git.io/vb4yH) to the 'plugins' section of your Babel config to enable transformation.)

```
import React from 'react';

export interface ChangeCardProps {}

export default function ChangeCard(props: ChangeCardProps) {
  return <div></div>;
}

```

**Comment by jedwards1211** [comment]
Okay, do you have `@babel/preset-typescript` installed?  It looks for that to determine whether to parse via Babel or Typescript

**Comment by muz3** [comment]
I don't have it installed.  My local repo use webpack only with babel-loader. How can I choose typescript to parse.

**Comment by jedwards1211** [comment]
Huh, are you loading `.ts`/`.tsx` files with `babel-loader` though or not?

I guess it's probably better if I just make it always parse `.ts(x)` with TypeScript...even if someone's using Babel to process their TS, it would still have to be parsable by the TypeScript compiler for type checking.

**Comment by jedwards1211** [comment]
I'll have a fix out soon, thanks for bringing this up!

**Comment by oltodo** [comment]
Hi, I'm getting the same troubles but with another Babel's library:

```
Command 'Material UI Codemorphs: Add useStyles hook' resulted in an error (/path/to/the/component/MyComponent.js: Support for the experimental syntax 'jsx' isn't currently enabled (4:10): 2 | 3 | export default function MyComponent() { > 4 | return <div></div>; | ^ 5 | } 6 | Add @babel/plugin-transform-react-jsx (https://git.io/vb4yd) to the 'plugins' section of your Babel config to enable transformation.)
```

This is a Create React App project without using Typescript. Any idea about it?

**Comment by jedwards1211** [comment]
The problem with create-react-app is that no babel config lives in your project folder, which makes it hard for any JS analysis tools outside of react-scripts to know what syntax your code uses.  But I'll investigate and see if there's a smart default behavior I can do in this case...

**Comment by oltodo** [comment]
Hmm, I see @jedwards1211.

So I have added a `babel.config.json` into my project's root with the following content:
 
```json
{
  "presets": ["react-app"]
}
```

I also have to add the following line into the `extension.js` file to avoid errors from the `react-app` Babel plugin:

```
process.env.NODE_ENV = 'development'
```

And it finally worked!

Maybe the extension can detect this is a create-react-app project and provide a dedicated Babel configuration WYT?

**Comment by jedwards1211** [comment]
I guess, I'd like to have a more thorough solution that would work for any project where the babel deps are transitive and no babel config lives in the project root, though I'm not sure if there's any reasonable way to do so...

I also wonder if create-react-app has an options that can affect the babel config even if you don't use a file in the project root?

I guess I could always fall back to just babel presets for standard syntax + jsx...
